twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/public/img/oeuvres': image
        '%kernel.project_dir%/public/css': style

when@test:
    twig:
        strict_variables: true
