vich_uploader:
    db_driver: orm
    metadata:
      type: attribute

    mappings:
      Oeuvre_image:
        uri_prefix: /img/oeuvres
        upload_destination: "%kernel.project_dir%/public/img/oeuvres"
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true


